### ISSUE TITLE
First picture of post to appear when linked on facebook / twitter and other external media. (it is a matter of post page metatags i think.) 

### ISSUE THREAD

**Issue by nnnarvaez** [wekuio/weku_portal#9]
From one user... 

```One thing I would like to see implemented to better promote weku on other , more established social media like facebook would be a photo appearing in the link when shared. I write recipes and a trail/travel blog and I often get asked for tips by my friends, instead of typing everything again or drop some links on relevant travel/tourism pages with a community interaction but it looks better if a photo appears with the link and more likely to get passed around/shared or looked at by others. ```

**Comment by wekuio** [comment]
When running 'wget' for a URL, it returns the 500 internal error.

Server Log:
Rendering error:  ReferenceError: window is not defined
========================================

  <-- GET /community-deals/@bigbear/we-must-teach-our-children-to-think-for-themselves 
Rendering error:  ReferenceError: window is not defined
    at App.render (/home/alexeyqian/web/lib/app/components/App.js:251:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34) ReferenceError: window is not def
ined
    at App.render (/home/alexeyqian/web/lib/app/components/App.js:251:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)

**Comment by wekuio** [comment]
Related: 
Rendering error:  ReferenceError: window is not defined

===========================================
  <-- GET /community-deals/@mirla33/sunset-at-playa-mansa-venezuela 
Rendering error:  ReferenceError: window is not defined


    at Header.render (/home/alexeyqian/web/lib/app/components/modules/Header.js:140:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/home/alexeyqian/web/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (/home/alexeyqian/web/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
    at ReactDOMComponent.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35) ReferenceError: window is not defined
    at Header.render (/home/alexeyqian/web/lib/app/components/modules/Header.js:140:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/home/alexeyqian/web/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (/home/alexeyqian/web/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
    at ReactDOMComponent.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/alexeyqian/web/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)

**Comment by wekuio** [comment]
After fixing the code in app.jsx and header.jsx, this issue is resolved.

if(typeof window !== 'undefined') is_iOS = (window.location.hostname.toLowerCase() == 'ios.weku.io');
